[phases.setup]
nixPkgs = ["nodejs_18", "python3", "pnpm-9_x", "openssl", "gcc", "gnumake"]

[phases.install]
cmds = ["npm install -g corepack@0.24.1 && corepack enable", "pnpm i"]

[phases.build]
cmds = []
